apiVersion: v1
kind: Service
metadata:
  name: secrets
  namespace: secrets
  labels:
    app: secrets

spec:
  type: NodePort
  selector:
    app: secrets
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

---

apiVersion: v1
kind: Pod
metadata:
  name: secrets
  namespace: secrets
  labels:
    app: secrets

spec:
  containers:
  - name: app
    imagePullPolicy: Always
    image: ghcr.io/bartr/secrets:0.1

    args:
      - --log

    ports:
    - containerPort: 8080

    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 2
      failureThreshold: 5
      periodSeconds: 10

    resources:
      limits:
        memory: 128Mi
        cpu: 200m
      requests:
        memory: 64Mi
        cpu: 100m

    volumeMounts:
      - name: secretsvol
        mountPath: "/secretsvol"
        readOnly: true

  volumes:
    - name: secretsvol
      secret:
        secretName: sample
